# Generated by Django 2.2.4 on 2019-09-04 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('91d9366c-cf07-11e9-8a5c-54bf644e2c92'), primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('91d89c30-cf07-11e9-a3d3-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
