# Generated by Django 3.0.4 on 2020-04-15 11:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200415_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('title', models.TextField(default='')),
            ],
            bases=('api.basemodel',),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('501aa2c8-7f0b-11ea-93ab-54bf644e2c92'), primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
