# Generated by Django 2.2.4 on 2019-09-04 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190904_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b68efb0a-cf07-11e9-9df2-54bf644e2c92'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b68ead1c-cf07-11e9-b79b-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
