# Generated by Django 2.2.4 on 2019-09-04 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190904_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('197b63e8-cf0a-11e9-ab29-54bf644e2c92'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('197b15f6-cf0a-11e9-9985-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
