# Generated by Django 2.2.4 on 2019-09-04 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190904_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a612bae-cf0b-11e9-86ad-54bf644e2c92'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a60ddc0-cf0b-11e9-8882-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
