# Generated by Django 2.2.4 on 2019-09-13 11:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190905_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49cf44d8-d61c-11e9-b014-54bf644e2c92'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49ce8376-d61c-11e9-b428-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
