# Generated by Django 2.2.4 on 2019-09-13 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190913_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('316a045c-d63b-11e9-90b9-54bf644e2c92'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3169681a-d63b-11e9-8662-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
