# Generated by Django 2.2.4 on 2019-09-14 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190913_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1da81652-d70e-11e9-a6fa-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
