# Generated by Django 2.2.4 on 2019-10-03 14:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190914_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b10fb452-e5e6-11e9-a77d-c0b5d71abd0e'), primary_key=True, serialize=False),
        ),
    ]
