# Generated by Django 2.2.4 on 2019-10-05 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191003_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa86b650-e730-11e9-b11b-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
